### PR TITLE
Full join with tests and documentation updates.

### PR DESCRIPTION
**Pull request by iamjpotts**

### CODE REVIEW

**Comment by simomat** [comment]
Just gave it a quick scan, looks very good so far! Will look closer soon. Sorry for the delay, I was on somewhat longer vacation.

**Comment by iamjpotts** [comment]
No worries.

**Comment by simomat** [comment]
So, I finally took a closer look. Thanks for adding that full join behavior, it totally fits in here. I like the API separation (own ```FullJoin``` class instead putting it all together into ```Join.java```). I should separate the other two join types like that, too.
The tests are nice and all fits together quite well.
What I miss is a ```.group(BiFunction<? super L, Stream<R>, Y> grouper)``` in addition to the combiner function, but that's no big deal, I can extend that.
I'm not sure about the actual join method ```Joiner.fullJoin()```. Both input streams are consumed and indexed at once which might affect memory efficiency. The other join types only index the right side of the join (handled in ```Cluster.java```).

I just modified the old join method so that the indexed right side can deliver items, which were not used while joining left items with right items:
```java
Cluster<KL, KR, R> rightCluster = createCluster(right, rightKeyFunction, matchPredicate);
Stream<Y> leftJoinResult = ... // the join of left elements against the rightCluster

// items that were not involved yet
Stream<Y> rightOuterResult = rightCluster.getUnresolvedItems().map(unmatchedRight);

return concat(leftJoinResult, rightOuterResult);
```

It works with your tests and does not need to consume the left side stream. (However, it would require to make the left stream sequential with ```leftStream.sequential()```. It's only possible the get the unmatched objects 'after' all left items are matched against right elements. That could not be ensured with a  parallel left input stream.)


Also, I don't know if we should match items, if the keys of both are ```null```. The full join matches all items from left and right that have ```null``` keys. My intuition says it's not right but I don't have a strong opinion about that. (Hmm I don't know how the other join types work in that case...)


If you don't mind, I would pull your changes, adapt the join as mentioned and let you make a review if you are interested.

**Comment by iamjpotts** [comment]
Good feedback. I agree on not matching up nulls, and added a test showing this is already the behavior in #2.

Neither the inner join, left join, nor full join will match up null keys.

**Pull request merged**
